### Topic to be covered 
    1.Intro
    2.Export to CSV
    3.Export to excel files
    4.Export to HTML files
    5.Export to JSON files
    6.Export to SQL

## 1.Intro

In [2]:
import pandas as pd
df = pd.DataFrame()

## Export to CSV

In [12]:
df = pd.read_csv('deliveries.csv')
df.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN

In [13]:
#  Suppose someone asks you to create a new dataset from this dataset,
# where the new column should contain the batsman's name and  the number of runs scored by each batsman, and then export this DataFrame as a CSV file.


temp_df = df.groupby('batsman')['batsman_runs'].sum()

In [18]:
temp_df.to_csv('batsman_runs.csv')

In [17]:
# jab aap csv file kholege to agar extra col nhi chaiye to aap likhoge index=False

temp_df.to_csv('batsman_runs.csv',index=False)

In [21]:
df.pivot_table(index = 'batsman',columns = 'bowling_team',values = 'batsman_runs',aggfunc = 'sum').to_csv("batsman_vs_team.csv")

## Export to Excel

In [22]:
df

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179073,11415,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,SR Watson,SL Malinga,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179074,11415,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179075,11415,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,1,0,1,SR Watson,run out,KH Pandya
179076,11415,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179077,11415,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,0,0,0,SN Thakur,lbw,NaN

In [25]:
temp_df = df.groupby('batsman')['batsman_runs'].sum().reset_index()
temp_df

            batsman  batsman_runs
0    A Ashish Reddy           280
1        A Chandila             4
2          A Chopra            53
3       A Choudhary            25
4       A Dananjaya             4
..              ...           ...
511     YV Takawale           192
512   Yashpal Singh            47
513     Younis Khan             3
514    Yuvraj Singh          2765
515          Z Khan           117

[516 rows x 2 columns]

In [27]:
# Change the above temp_df into excel

temp_df.to_excel('batsman_runs.xlsx')

In [28]:
# If you want, you can also store it in a particular sheet.

temp_df.to_excel('output.xlsx',sheet_name = 'batsman_runs')

In [29]:
# Suppose you have to create an Excel file that contains multiple sheets.
# What we are doing is storing the batsman's runs in one sheet and the pivot table in another sheet.


temp_df2 = df.pivot_table(index = 'batsman',columns = 'bowling_team',values = 'batsman_runs',aggfunc = 'sum')

So, what you have to do below? You have to write the code in such a way that whenever you have an Excel file and you want to work with multiple sheets in that file, you use an Excel Writer object.

First, you create an object of the Excel Writer class, and then you provide the name of your file. We can call it `output.xlsx` as `writer`.

After that, you take all your DataFrames and write them one by one. For example, if my first DataFrame is `temp_df`, I call `temp_df.to_excel()` and pass the writer object and specify the sheet name.

Then, for my second DataFrame, I do the same thing: `temp_df2.to_excel()`, pass the writer object, and specify another sheet name.

So basically, what am I doing? I am creating a **single Excel file**, but I am working with **multiple sheets** inside that same file. That's why, when I run the code, it creates one Excel file containing both sheets.

In [30]:
with pd.ExcelWriter('output.xlsx') as writer:
    temp_df.to_excel(writer,sheet_name = 'Sheet_name_1')
    temp_df2.to_excel(writer,sheet_name = 'Sheet_name_2')

## 4.Export to HTML files

In [31]:
# You can convert your Pandas DataFrame into HTML.
# Let's say you want to write your analysis in the form of a blog, and you want to display your analysis as a table in the blog.

In [33]:
# We are creating a DataFrame using `df.pivot_table`. This pivot table contains information related to overs and balls. 

df.query('batsman_runs == 6').pivot_table(index='over',columns='ball',values='batsman_runs',aggfunc='count').to_html('sixes_heatmap.html')

## 5.Export to JSON

In [34]:
df

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179073,11415,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,SR Watson,SL Malinga,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179074,11415,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179075,11415,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,1,0,1,SR Watson,run out,KH Pandya
179076,11415,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179077,11415,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,0,0,0,SN Thakur,lbw,NaN

In [36]:
# From the `df` above, you have to create a JSON. In that JSON, 
# there will be the name of each batsman, the name of the team they played for, and the number of runs they scored.
 

df.groupby(['batting_team','batsman'])['batsman_runs'].sum().unstack().to_json('ipl.json')

## 6.Export to SQL

In [41]:
import pymysql
from sqlalchemy import create_engine

In [ ]:
engine = create_engine("mysql+pymysql://root:@localhost/campusx")
df.to_sql('ipl',con = engine, if_exists = 'append')